<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "news_subheader"
 *
 * Auto generated by Extension Builder 2017-06-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'News Subheader',
    'description' => 'Adds a subheader field to News',
    'category' => 'plugin',
    'author' => 'Sven Juergens',
    'author_email' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => false,
    'createDirs' => '',
    'clearCacheOnLoad' => true,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.9.99',
            'news' => '6.0.0-6.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
